// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Unalive_WebManagement.Data;

#nullable disable

namespace Unalive_WebManagement.DAL.Migrations
{
    [DbContext(typeof(UnaliveDbContext))]
    [Migration("20260326105031_InitialNewSchema")]
    partial class InitialNewSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Unalive_WebManagement.Models.AbilitiesSet", b =>
                {
                    b.Property<int>("CharacterTacticId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterAttackId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterPassiveId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterSkillId")
                        .HasColumnType("int");

                    b.HasKey("CharacterTacticId");

                    b.HasIndex("CharacterAttackId");

                    b.HasIndex("CharacterPassiveId");

                    b.HasIndex("CharacterSkillId");

                    b.ToTable("AbilitiesSets");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.Announcement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnnouncementId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("AnnouncementId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.BundleItem", b =>
                {
                    b.Property<int>("BundleId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("BundleId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("BundleItems");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.CharacterAttack", b =>
                {
                    b.Property<int>("CharacterAttackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterAttackId"));

                    b.Property<int>("AP")
                        .HasColumnType("int");

                    b.Property<int>("CritDmg")
                        .HasColumnType("int");

                    b.Property<int>("CritRate")
                        .HasColumnType("int");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockedState")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YuanPressure")
                        .HasColumnType("int");

                    b.HasKey("CharacterAttackId");

                    b.ToTable("CharacterAttacks");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.CharacterPassive", b =>
                {
                    b.Property<int>("CharacterPassiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterPassiveId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockedState")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CharacterPassiveId");

                    b.ToTable("CharacterPassives");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.CharacterPvP", b =>
                {
                    b.Property<int>("CharacterTacticId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CharacterTacticId");

                    b.ToTable("CharacterPvPs");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.CharacterSkill", b =>
                {
                    b.Property<int>("CharacterSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterSkillId"));

                    b.Property<int>("CritDmg")
                        .HasColumnType("int");

                    b.Property<int>("CritRate")
                        .HasColumnType("int");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockedState")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SP")
                        .HasColumnType("int");

                    b.Property<int>("YuanPressure")
                        .HasColumnType("int");

                    b.HasKey("CharacterSkillId");

                    b.ToTable("CharacterSkills");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.CharacterStat", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterId"));

                    b.Property<int>("MaxHealth")
                        .HasColumnType("int");

                    b.Property<int>("MoveRange")
                        .HasColumnType("int");

                    b.HasKey("CharacterId");

                    b.ToTable("CharacterStats");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.GemBundle", b =>
                {
                    b.Property<int>("GemBundleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GemBundleId"));

                    b.Property<string>("BundleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("BundlePrice")
                        .HasColumnType("real");

                    b.HasKey("GemBundleId");

                    b.ToTable("GemBundles");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.ItemBundle", b =>
                {
                    b.Property<int>("ItemBundleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemBundleId"));

                    b.Property<string>("BundleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("BundlePrice")
                        .HasColumnType("real");

                    b.HasKey("ItemBundleId");

                    b.ToTable("ItemBundles");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("NotificationMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Read")
                        .HasColumnType("bit");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<int>("AccusedId")
                        .HasColumnType("int");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.HasIndex("AccusedId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("SenderId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.ShopOrder", b =>
                {
                    b.Property<int>("ShopOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShopOrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("TotalAmount")
                        .HasColumnType("real");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ShopOrderId");

                    b.HasIndex("UserId");

                    b.ToTable("ShopOrders");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.ShopOrderDetail", b =>
                {
                    b.Property<int>("ShopOrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShopOrderDetailId"));

                    b.Property<int?>("ItemBundleId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ShopOrderId")
                        .HasColumnType("int");

                    b.Property<float>("UnitPrice")
                        .HasColumnType("real");

                    b.HasKey("ShopOrderDetailId");

                    b.HasIndex("ItemBundleId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ShopOrderId");

                    b.ToTable("ShopOrderDetails");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StaffId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.TopUpHistory", b =>
                {
                    b.Property<int>("TopUpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TopUpId"));

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("GemBundleId")
                        .HasColumnType("int");

                    b.Property<int>("GemsAmount")
                        .HasColumnType("int");

                    b.Property<string>("PaymentGateway")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("RealMoneyAmount")
                        .HasColumnType("real");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TopUpId");

                    b.HasIndex("GemBundleId");

                    b.HasIndex("UserId");

                    b.ToTable("TopUpHistories");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool>("Banned")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.UserBundle", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemBundleId")
                        .HasColumnType("int");

                    b.Property<int?>("GemBundleId")
                        .HasColumnType("int");

                    b.Property<int>("Remaining")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ItemBundleId", "GemBundleId");

                    b.HasIndex("GemBundleId");

                    b.HasIndex("ItemBundleId");

                    b.ToTable("UserBundles");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.UserItem", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ShopOrderId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ShopOrderId");

                    b.ToTable("UserItems");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.AbilitiesSet", b =>
                {
                    b.HasOne("Unalive_WebManagement.Models.CharacterAttack", null)
                        .WithMany()
                        .HasForeignKey("CharacterAttackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unalive_WebManagement.Models.CharacterPassive", null)
                        .WithMany()
                        .HasForeignKey("CharacterPassiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unalive_WebManagement.Models.CharacterSkill", null)
                        .WithMany()
                        .HasForeignKey("CharacterSkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unalive_WebManagement.Models.CharacterPvP", null)
                        .WithMany()
                        .HasForeignKey("CharacterTacticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.Announcement", b =>
                {
                    b.HasOne("Unalive_WebManagement.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Unalive_WebManagement.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.BundleItem", b =>
                {
                    b.HasOne("Unalive_WebManagement.Models.ItemBundle", null)
                        .WithMany()
                        .HasForeignKey("BundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unalive_WebManagement.Models.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.CharacterPvP", b =>
                {
                    b.HasOne("Unalive_WebManagement.Models.CharacterStat", null)
                        .WithMany()
                        .HasForeignKey("CharacterTacticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.Notification", b =>
                {
                    b.HasOne("Unalive_WebManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.Report", b =>
                {
                    b.HasOne("Unalive_WebManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("AccusedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Unalive_WebManagement.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("ApprovedBy");

                    b.HasOne("Unalive_WebManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.ShopOrder", b =>
                {
                    b.HasOne("Unalive_WebManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.ShopOrderDetail", b =>
                {
                    b.HasOne("Unalive_WebManagement.Models.ItemBundle", null)
                        .WithMany()
                        .HasForeignKey("ItemBundleId");

                    b.HasOne("Unalive_WebManagement.Models.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unalive_WebManagement.Models.ShopOrder", null)
                        .WithMany()
                        .HasForeignKey("ShopOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.TopUpHistory", b =>
                {
                    b.HasOne("Unalive_WebManagement.Models.GemBundle", null)
                        .WithMany()
                        .HasForeignKey("GemBundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unalive_WebManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.UserBundle", b =>
                {
                    b.HasOne("Unalive_WebManagement.Models.GemBundle", null)
                        .WithMany()
                        .HasForeignKey("GemBundleId");

                    b.HasOne("Unalive_WebManagement.Models.ItemBundle", null)
                        .WithMany()
                        .HasForeignKey("ItemBundleId");

                    b.HasOne("Unalive_WebManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.UserItem", b =>
                {
                    b.HasOne("Unalive_WebManagement.Models.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unalive_WebManagement.Models.ShopOrder", null)
                        .WithMany()
                        .HasForeignKey("ShopOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unalive_WebManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
