// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Unalive_WebManagement.Data;

#nullable disable

namespace Unalive_WebManagement.DAL.Migrations
{
    [DbContext(typeof(UnaliveDbContext))]
    partial class UnaliveDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Unalive_WebManagement.Models.AbilitiesSet", b =>
                {
                    b.Property<int>("CharacterTacticId")
                        .HasColumnType("integer");

                    b.Property<int>("CharacterAttackId")
                        .HasColumnType("integer");

                    b.Property<int>("CharacterPassiveId")
                        .HasColumnType("integer");

                    b.Property<int>("CharacterSkillId")
                        .HasColumnType("integer");

                    b.HasKey("CharacterTacticId");

                    b.HasIndex("CharacterAttackId");

                    b.HasIndex("CharacterPassiveId");

                    b.HasIndex("CharacterSkillId");

                    b.ToTable("AbilitiesSets");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.Announcement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnnouncementId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("AnnouncementId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.CharacterAttack", b =>
                {
                    b.Property<int>("CharacterAttackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CharacterAttackId"));

                    b.Property<int>("AP")
                        .HasColumnType("integer");

                    b.Property<int>("CritDmg")
                        .HasColumnType("integer");

                    b.Property<int>("CritRate")
                        .HasColumnType("integer");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("LockedState")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YuanPressure")
                        .HasColumnType("integer");

                    b.HasKey("CharacterAttackId");

                    b.ToTable("CharacterAttacks");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.CharacterPassive", b =>
                {
                    b.Property<int>("CharacterPassiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CharacterPassiveId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("LockedState")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CharacterPassiveId");

                    b.ToTable("CharacterPassives");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.CharacterPvP", b =>
                {
                    b.Property<int>("CharacterTacticId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CharacterTacticId");

                    b.ToTable("CharacterPvPs");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.CharacterSkill", b =>
                {
                    b.Property<int>("CharacterSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CharacterSkillId"));

                    b.Property<int>("CritDmg")
                        .HasColumnType("integer");

                    b.Property<int>("CritRate")
                        .HasColumnType("integer");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("LockedState")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SP")
                        .HasColumnType("integer");

                    b.Property<int>("YuanPressure")
                        .HasColumnType("integer");

                    b.HasKey("CharacterSkillId");

                    b.ToTable("CharacterSkills");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.CharacterStat", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CharacterId"));

                    b.Property<int>("MaxHealth")
                        .HasColumnType("integer");

                    b.Property<int>("MoveRange")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId");

                    b.ToTable("CharacterStats");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.GemBundle", b =>
                {
                    b.Property<int>("GemBundleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GemBundleId"));

                    b.Property<string>("BundleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("BundlePrice")
                        .HasColumnType("real");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("GemBundleId");

                    b.ToTable("GemBundles");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("NotificationMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("Read")
                        .HasColumnType("smallint");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.HasKey("NotificationId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.OrderTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<string>("CounterAccountBankId")
                        .HasColumnType("text");

                    b.Property<string>("CounterAccountBankName")
                        .HasColumnType("text");

                    b.Property<string>("CounterAccountName")
                        .HasColumnType("text");

                    b.Property<string>("CounterAccountNumber")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OrderCode")
                        .HasColumnType("bigint");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentLinkId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("TransactionDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VirtualAccountName")
                        .HasColumnType("text");

                    b.Property<string>("VirtualAccountNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OrderTransactions");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.PlayerOnlineHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DailyActiveUsers")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OnlineCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PlayerOnlineHistories");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportId"));

                    b.Property<int>("AccusedId")
                        .HasColumnType("integer");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("text");

                    b.Property<short>("Approved")
                        .HasColumnType("smallint");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.HasKey("ReportId");

                    b.HasIndex("AccusedId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("SenderId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.ShopOrder", b =>
                {
                    b.Property<int>("ShopOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShopOrderId"));

                    b.Property<string>("AccountName")
                        .HasColumnType("text");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("text");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<long>("AmountPaid")
                        .HasColumnType("bigint");

                    b.Property<long>("AmountRemaining")
                        .HasColumnType("bigint");

                    b.Property<string>("Bin")
                        .HasColumnType("text");

                    b.Property<string>("CancelUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CanceledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    b.Property<string>("CheckoutUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastTransactionUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("OrderCode")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentLinkId")
                        .HasColumnType("text");

                    b.Property<string>("PlayerEmail")
                        .HasColumnType("text");

                    b.Property<string>("PlayerUserName")
                        .HasColumnType("text");

                    b.Property<string>("QrCode")
                        .HasColumnType("text");

                    b.Property<string>("ReturnUrl")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<float>("TotalAmount")
                        .HasColumnType("real");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ShopOrderId");

                    b.HasIndex("UserId");

                    b.ToTable("ShopOrders");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.ShopOrderDetail", b =>
                {
                    b.Property<int>("ShopOrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShopOrderDetailId"));

                    b.Property<int?>("GemBundleId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("ShopOrderId")
                        .HasColumnType("integer");

                    b.Property<int?>("SkinAndCharacterBundleId")
                        .HasColumnType("integer");

                    b.Property<float>("UnitPrice")
                        .HasColumnType("real");

                    b.HasKey("ShopOrderDetailId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ShopOrderId");

                    b.HasIndex("SkinAndCharacterBundleId");

                    b.ToTable("ShopOrderDetails");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.SkinAndCharacterBundle", b =>
                {
                    b.Property<int>("SkinAndCharacterBundleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SkinAndCharacterBundleId"));

                    b.Property<string>("BundleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("BundlePrice")
                        .HasColumnType("real");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("SkinAndCharacterBundleId");

                    b.ToTable("SkinAndCharacterBundles");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StaffId"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("StaffId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.TopUpHistory", b =>
                {
                    b.Property<int>("TopUpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TopUpId"));

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GemBundleId")
                        .HasColumnType("integer");

                    b.Property<int>("GemsAmount")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentGateway")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("RealMoneyAmount")
                        .HasColumnType("real");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("TopUpId");

                    b.HasIndex("GemBundleId");

                    b.HasIndex("UserId");

                    b.ToTable("TopUpHistories");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<short>("Banned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<DateTimeOffset?>("BannedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EmailVerificationToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("EmailVerificationTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<short>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<short>("IsOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("LastOnline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.UserBanLog", b =>
                {
                    b.Property<int>("UserBanLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserBanLogId"));

                    b.Property<string>("BanReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BannedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("BannedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("BannedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserBanLogId");

                    b.HasIndex("BannedBy");

                    b.HasIndex("UserId");

                    b.ToTable("UserBanLogs");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.UserBundle", b =>
                {
                    b.Property<int>("UserBundleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserBundleId"));

                    b.Property<int?>("GemBundleId")
                        .HasColumnType("integer");

                    b.Property<int>("Remaining")
                        .HasColumnType("integer");

                    b.Property<int?>("SkinAndCharacterBundleId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserBundleId");

                    b.HasIndex("GemBundleId");

                    b.HasIndex("SkinAndCharacterBundleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserBundles");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.UserItem", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("ShopOrderId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "ItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ShopOrderId");

                    b.ToTable("UserItems");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.AbilitiesSet", b =>
                {
                    b.HasOne("Unalive_WebManagement.Models.CharacterAttack", null)
                        .WithMany()
                        .HasForeignKey("CharacterAttackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unalive_WebManagement.Models.CharacterPassive", null)
                        .WithMany()
                        .HasForeignKey("CharacterPassiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unalive_WebManagement.Models.CharacterSkill", null)
                        .WithMany()
                        .HasForeignKey("CharacterSkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unalive_WebManagement.Models.CharacterPvP", null)
                        .WithMany()
                        .HasForeignKey("CharacterTacticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.Announcement", b =>
                {
                    b.HasOne("Unalive_WebManagement.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Unalive_WebManagement.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.CharacterPvP", b =>
                {
                    b.HasOne("Unalive_WebManagement.Models.CharacterStat", null)
                        .WithMany()
                        .HasForeignKey("CharacterTacticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.Notification", b =>
                {
                    b.HasOne("Unalive_WebManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.Report", b =>
                {
                    b.HasOne("Unalive_WebManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("AccusedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Unalive_WebManagement.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("ApprovedBy");

                    b.HasOne("Unalive_WebManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.ShopOrder", b =>
                {
                    b.HasOne("Unalive_WebManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.ShopOrderDetail", b =>
                {
                    b.HasOne("Unalive_WebManagement.Models.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unalive_WebManagement.Models.ShopOrder", "ShopOrder")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ShopOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Unalive_WebManagement.Models.SkinAndCharacterBundle", null)
                        .WithMany()
                        .HasForeignKey("SkinAndCharacterBundleId");

                    b.Navigation("ShopOrder");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.TopUpHistory", b =>
                {
                    b.HasOne("Unalive_WebManagement.Models.GemBundle", null)
                        .WithMany()
                        .HasForeignKey("GemBundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unalive_WebManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.UserBanLog", b =>
                {
                    b.HasOne("Unalive_WebManagement.Models.Staff", "BannedByNavigation")
                        .WithMany()
                        .HasForeignKey("BannedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unalive_WebManagement.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BannedByNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.UserBundle", b =>
                {
                    b.HasOne("Unalive_WebManagement.Models.GemBundle", "GemBundle")
                        .WithMany()
                        .HasForeignKey("GemBundleId");

                    b.HasOne("Unalive_WebManagement.Models.SkinAndCharacterBundle", "SkinAndCharacterBundle")
                        .WithMany()
                        .HasForeignKey("SkinAndCharacterBundleId");

                    b.HasOne("Unalive_WebManagement.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GemBundle");

                    b.Navigation("SkinAndCharacterBundle");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.UserItem", b =>
                {
                    b.HasOne("Unalive_WebManagement.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unalive_WebManagement.Models.ShopOrder", "ShopOrder")
                        .WithMany()
                        .HasForeignKey("ShopOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Unalive_WebManagement.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("ShopOrder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Unalive_WebManagement.Models.ShopOrder", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
